config/routes.rb
Rails.application.routes.draw do


  # devise_for :users  <= 管理者ユーザログイン中に、ユーザ登録画面へ遷移できるようにルート変更
  devise_for :users, controllers: { registrations: 'registrations' }
  
  # get 'patients/index'
  root to: "patients#index"
  resources :patients, only: [:index, :new, :create, :show, :edit, :update] 
  resources :addresses, only: [:edit, :update]
  resources :contacts, only: [:edit, :update]
  resources :admissions, only: [:update]
  resources :pending_admission_requests, only: [:edit, :update]
  resources :discharges, only: [:update]


end

app/models/patient.rb
class Patient < ApplicationRecord

  #--- association ---#
  has_many :addresses
  has_many :contacts
  # join でのテーブル結合のため、admmissions テーブルとはhas_one　だが、has_many にしておく  
  # has_one :admission
  has_many :admissions

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :gender
  belongs_to :blood_abo
  belongs_to :blood_rh
  belongs_to :transfer
  has_one_attached :image


  #--- validate ---#
  validates :full_name, presence: true
  validates :full_name_kana, presence: true


  # formオブジェクトエラーのため、一旦コメント
  # validates :fa_patient_id, presence: true
  # validates :fa_patient_id, numericality: true
  # validates_uniqueness_of :fa_patient_id

  # validates :date_of_birth, presence: true
  validates :gender_id, numericality: { other_than: 1, message: "can't be blank"} 
  validates :transfer_id, numericality: { other_than: 1, message: "can't be blank"} 

  with_options presence: true, format: { with: /\A[ァ-ヶー]+\z/, message: '全角カタカナ文字を使用してください' } do
    validates :full_name_kana
  end



end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :authenticate_user!, only: [:index]

  def index
    if params[:ward_num] == nil
      @patients = Patient.joins(:admissions).where(admissions: { ward_id: current_user.ward_id }).order("roombed_id ASC")
      @ward_num = current_user.ward_id
    else
      @patients = Patient.joins(:admissions).where(admissions: { ward_id: params[:ward_num] }).order("roombed_id ASC")
      @ward_num = params[:ward_num]
    end
    @patient_count = @patients.count

    @ward = Ward.find([@ward_num])
    @ward_max_num_beds = @ward.first.max_num_beds

    @male_patient_count = @patients.where(gender_id: '2').count
    @female_patient_count = @patients.where(gender_id: '3').count
    @lgbt_patient_count = @patients.where(gender_id: '4').count
    @doppo_patient_count = @patients.where(transfer_id: '2').count
    @goso_patient_count = @patients.where(transfer_id: '3').count
    @tanso_patient_count = @patients.where(transfer_id: '4').count
  end



  
  def show
    @patient = Patient.find(params[:id])
    @ward_num = @patient.admissions.first&.ward_id
    @admission = @patient.admissions.first
    @address = @patient.addresses.first
  end



  def new
    # @patient = Patient.new
    @pat_add_cont_adm = PatAddContAdm.new

  end


  def create
    @pat_add_cont_adm = PatAddContAdm.new(pat_add_cont_adm_params)
    date = params.require(:pat_add_cont_adm).permit(:date_of_birth)

    if date["date_of_birth(1i)"] != "" && date["date_of_birth(2i)"] != "" && date["date_of_birth(3i)"] != "" 
      date_of_birth = Date.parse( date["date_of_birth(1i)"] + "-" + date["date_of_birth(2i)"] + "-" + date["date_of_birth(3i)"] )
      @pat_add_cont_adm = PatAddContAdm.new(pat_add_cont_adm_params.merge(date_of_birth: date_of_birth))

      if @pat_add_cont_adm.valid?
        @pat_add_cont_adm.save
        redirect_to root_path
      else
        render :new
      end
    else
      # 生年月日に問題がある場合は、登録画面へ戻す
      # エラーコードは修正必要
      render :new
    end
  end


  def edit
    @patient = Patient.find(params[:id])
  end

  def update
    @patient = Patient.find(params[:id])
    if @patient.update(patient_params)
      redirect_to "/patients/#{@patient.id}"
    else
      render :edit
    end

  end



  private

  # :date_of_birth属性は後でmergeする
# , :ward_num パラムスにいる？
  def pat_add_cont_adm_params
    params.require(:pat_add_cont_adm).permit(:fa_patient_id, :full_name, :full_name_kana, :gender_id, :blood_abo_id, :blood_rh_id, :transfer_id, :pmhx, :description, :image, :postal_code, :prefecture_id, :city, :house_number, :building_name, :phone_number, :phone_number2, :full_name1, :full_name_kana1, :relation1, :phone_number11, :phone_number12, :description1, :full_name2, :full_name_kana2, :relation2, :phone_number21, :phone_number22, :description2, :ward_id, :roombed_id, :admission_date, :hxofadm)
  end



def patient_params
  params.require(:patient).permit(:fa_patient_id, :full_name, :full_name_kana, :gender_id, :blood_abo_id, :blood_rh_id, :transfer_id, :pmhx, :description, :image)
end



end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_main-center-show.html.erb
<div class="main-center-show">
<%# ここに左右の矢印挿入し、患者を次の患者へ切り替え %>

  <div class="main-center-show1">

<%# 上側  患者の基本情報 %>
    <div class="upper-block">


      <div class="photo">
        <%  if @patient.image.attached? %>
          <%= image_tag @patient.image.variant(resize: '160x120'), class: "patient-img" %>
        <% else %>
          <%= image_tag 'dummy.png', class: "patient-img" %>
        <% end %>
      </div>

      <div  class="basic_info1">
        <br>
        ID：<%= @patient.fa_patient_id %><br>
        フリガナ：<%= @patient.full_name_kana %><br>
        名前：<%= @patient.full_name %><br>
        性別：<%= @patient.gender.name %><br>
      </div>


      <div  class="basic_info2">
        <br>
          <div>生年月日：</div>
          <div id="inputBirth"><%= @patient.date_of_birth %></div>
          <div class="age"></div>
      </div>


      <div  class="basic_info3">
        <br>
        血液型：<%= @patient.blood_abo.name %> <%= @patient.blood_rh.name %><br>
        移送区分：<%= @patient.transfer.name %><br>
      </div>

      <div  class="basic_info4">
        <br>
        ベッド番号：
          <%= Roombed.find_by(id: @admission.roombed_id)&.name  %><br>
        主治医：高知土佐男<br>
        担当Ns：土佐高知子
      </div>

      <div  class="basic_info5">
        <br>

<%# 入院ステータスが外来ならば、 %>
        <% if @ward_num == 2 %>
          <div class="basic-info-edit">
            <%= link_to "入院待ちへ", admission_path, method: :put, class: "adm-status-chg-btn" %> 
          </div>
<%# 入院ステータスが入院まちならば、 %>
        <% elsif @ward_num == 9 %> 
          <div class="basic-info-edit">
            <%= link_to "入院処理", edit_pending_admission_request_path, method: :get, class: "adm-status-chg-btn" %> 
          </div>
          <br>
          <br>
          <div class="basic-info-edit">
            <%= link_to "外来へ戻す", pending_admission_request_path(:key => "outpatient"), method: :put, class: "adm-status-chg-btn" %> 
          </div>
<%# 入院ステータスが入院中ならば、 %>
        <% else %>
          <div class="basic-info-edit">
            <%= link_to "退院処理", discharge_path, method: :put, class: "adm-status-chg-btn" %> 
          </div>
        <% end %>
      </div>
    </div>


<%# 下側  タブでの詳細情報 %>
    <div class="lower-block">
      <main>
        <ul class="tabs">
          <li><a href="" class="active">基本情報</a></li>
          <li><a href="" >住所</a></li>
          <li><a href="" >連絡先</a></li>
          <li><a href="" >アレルギー</a></li>
          <li><a href="" >感染症</a></li>
          <li><a href="" >食事</a></li>
          <li><a href="" >健康保険</a></li>
          <li><a href="" >入院歴</a></li>
        </ul>


        <ul class="contents">
<%#------- 基本情報　------- %>
          <li class="active">
            <div class="additional-basic-info">
              <div class="basic-info">
                既往歴<br>
                <%= @patient.pmhx %>

                <br>
                <br>
                補足<br>
                <%= @patient.description %>
              </div>
              <div class="basic-info-edit">
                <%= link_to "基本情報の編集", edit_patient_path, method: :get, class: "patient-edit-btn" %> 
              </div>
            </div>
          </li>
<%#------- 住所　------- %>
          <li>
            <div class="additional-basic-info">
              <div class="pt-address">
                住所<br>
                <%= @address.postal_code %><br>
                <%= Prefecture.find_by(id: @address.prefecture_id)&.name  %>
                <%= @address.city %>
                <%= @address.house_number %>
                <%= @address.building_name %>
                <br>
                <br>
                本人連絡先<br>
                <%= @address.phone_number %><br>
                <%= @address.phone_number2 %>
              </div>
              <div class="basic-info-edit">
                <%= link_to "住所の編集", edit_address_path, method: :get, class: "patient-edit-btn" %> 
              </div>
            </div>

          </li>
<%#------- 連絡先  ------- %>
          <li>
            <div class="additional-basic-info">
              <div class="pt-contact">
                連絡先１<br>
                  <div class="em-contact1">
                    <% @contact = @patient.contacts.first %>
                    <%= @contact.full_name1 %>（ <%= @contact.full_name_kana1 %> ）<br>
                    本人との関係：<%= @contact.relation1 %><br>
                    電話番号1：<%= @contact.phone_number11 %><br>
                    電話番号2：<%= @contact.phone_number12 %><br>
                  </div>

                  <br>
                  <br>

                連絡先２<br>
                  <div class="em-contact2">
                    <%= @contact.full_name2 %>（ <%= @contact.full_name_kana2 %> ）<br>
                    本人との関係：<%= @contact.relation2 %><br>
                    電話番号1：<%= @contact.phone_number21 %><br>
                    電話番号2：<%= @contact.phone_number22 %><br>
                  </div>
              </div>
              <div class="basic-info-edit">
                <%= link_to "連絡先の編集", edit_contact_path, method: :get, class: "patient-edit-btn" %> 
              </div>
            </div>
          </li>





<%#------- アレルギー  ------- %>
          <li>アレルギー
          卵、さば、アルコール、
          </li>
<%#------- 感染症  ------- %>
          <li>感染症
          HCV, HBV, MRSA・・・・
          </li>
<%#------- 食事  ------- %>
          <li>食事
            食事形態　普通、五分粥、キザミ食、。。。。
          </li>
<%#------- 健康保険  ------- %>
          <li>健康保険
            国民健康保険、船員保険、社会保険、後期高齢者医療制度、
          </li>
<%#------- 入院歴  ------- %>
          <li>入院歴
            入院歴
          </li>
        </ul>

      </main>
    </div>
  </div>
</div>

app/views/patients/_main-center.html.erb
<div class="main-center">

  <table>
    <tr>
  <%# # もし外来患者リストなら、部屋番号はなし# %>
      <th>部屋番号</th>
      <th>患者ID</th>
      <th>名前</th>
      <th>フリガナ</th>
      <th>性別</th>
      <th>生年月日</th>
      <th>年齢</th>
  <%# # もし外来患者リストなら、入院形態はなし# %>
      <th>入院形態</th>
    </tr>

    <% @patients.each do |patient| %>
      <tr>
  <%# # もし外来患者リストなら、部屋番号はなし# %>
        <%# <td> 部屋番号 </td> %>
        <%# <td><%= patient.admission.ward_id %>
        <td id="roombed">
          <% admission = patient.admissions.first %>
          <%= Roombed.find_by(id: admission.roombed_id)&.name  %>
        </td>

        <td><%=link_to patient.fa_patient_id, "/patients/#{patient.id}" %></td>
        <td><%=link_to patient.full_name, "/patients/#{patient.id}" %></td>
        <td><%=link_to  patient.full_name_kana, "/patients/#{patient.id}" %></td>
        <td><%= patient.gender.name %></td>
        <td id="inputBirth"><%= patient.date_of_birth %></td>
        <td class="age">  </td>
  <%# # もし外来患者リストなら、入院形態はなし# %>
        <td> 入院形態 </td>
      </tr>
    <% end %>

  </table>

</div>

app/views/patients/_main-footer.html.erb
<div class="main-footer">
</div>

app/views/patients/_main-header-show.html.erb
<div class="main-header">
  <div class="main-header-wrap">

    <div class="main-header-ward">
      <select name="ward-num">
        <option value='2'>外来</option>
        <option value='3'>1病棟</option>
        <option value='4'>2病棟</option>
      </select>
    </div>



    <div class="main-header-contents">
    </div>
  </div>
</div>

app/views/patients/_main-header.html.erb
<div class="main-header">
  <div class="main-header-wrap">

    <%= form_with url: root_path, method: :get, local: true do |f| %>
    <div class="main-header-search">
      <%= f.collection_select(:ward_num, Ward.all, :id, :name, {selected: @ward_num}, {class:"main-header-ward", id:"ward"}) %>
      <%# ボタン %>
      <div class="ward_search-btn-contents">
        <%= f.submit "検索" ,class:"ward_search-btn" %>
      </div>
      <%# /ボタン %>
    </div>
  <% end %>




  <% if action_name == 'index' %>
    <div class="main-header-contents">
      <div class="pt-count-wrap">
        <div>患者数</div>
          <div  class="contents-font">
            <div>現在数 <%= @patient_count %> 名</div>
            <div>総床数  <%= @ward_max_num_beds %> 名</div>
            <div>　</div>
          </div>
      </div>

      <div class="gender-count-wrap">
          <div>性別</div>
          <div  class="contents-font">
            <div>男性  <%= @male_patient_count %> 名</div>
            <div>女性  <%= @female_patient_count %> 名</div>
            <div>その他  <%= @lgbt_patient_count %> 名</div>
        </div>
      </div>

      <div class="inf-count-wrap">
          <div>感染症</div>
          <div  class="contents-font">
            <div>HCV  1 名</div>
            <div>HBV  0 名</div>
            <div>MRSA 3 名</div>
        </div>
      </div>
      <div class="trf-count-wrap">
          <div>移送区分</div>
          <div  class="contents-font">
            <div>担送  <%= @tanso_patient_count %> 名</div>
            <div>護送  <%= @goso_patient_count %> 名</div>
            <div>独歩  <%= @doppo_patient_count %> 名</div>
        </div>
      </div>
    </div>
  <% end %>


  </div>
</div>

app/views/patients/_side_bar.html.erb
<div class="side-bar-header">
    <h1 class="heading-012"><span>eKar</span></h1>
    <h4>患者情報管理</h4>
</div>

<div class="side-bar-center">

  <div class="user-info">
    <div> ID :
       <%= current_user.employee_id %>
    </div> 
    <div> 使用者 : 
      <%= link_to current_user.full_name, root_path(current_user), class: "current_user_display" %> さん
    </div>
    <div class="current_user_occupation"> 職種 :
      <%= current_user.occupation.name %> 
    </div>
    <div class="log-out-head">
      <div> 病棟 :
       <%= current_user.ward.name %> 
       </div>
      <div class="log-out">
          <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout" %> 
       </div>


    </div>
  </div>



  <div class="pts-index">
    <%= link_to '患者情報一覧', root_path, class: "pts-index-button" %> 
  </div>

  <div class="new-pt-regi">
    <%= link_to '新規患者情報登録', new_patient_path, class: "new-pt-regi-button" %> 
  </div>


  <% if current_user.group_id == 3 %>
    <div class="user-regi">
      <p>管理者用</p>
      <%= link_to '使用者登録', new_user_registration_path, class: "sign-up" %>
    </div>
  <% end %>





</div>

app/views/patients/index.html.erb
<div class="wrapper">
  <div class="side-bar">
    <%= render "side_bar" %>
  </div>
  <div class="main-part">
    <%= render "main" %>
  </div>
</div>

app/views/patients/new.html.erb
<%# <%= form_with model: @patient, url: patients_path, method: :post, class: 'registration-main', local: true do |f| %>
<%= form_with model: @pat_add_cont_adm, url: patients_path, method: :post, class: 'registration-main', local: true do |f| %> 


<div class='form-wrap'>
  <div class='form-header'>
    <h1 class='form-header-text'>
      新規-患者情報の入力
    </h1>
  </div>

  <%= render "shared/error_messages", model: f.object %>


<%#------ patients テーブル部分 ------%>
  <div class="form-group">
    <%# 画像 %>
    <div class="img-upload">

      <label class="form-text">画像</label>

      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image, id:"item-image" %>
      </div>
    </div>
    <%# /画像 %>
  </div>


  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">患者ID</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_area :fa_patient_id, class:"input-default", id:"fa_patient_id", placeholder:"ID", maxlength:"10" %>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">名前（姓名）</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_area :full_name, class:"input-default", id:"full_name", placeholder:"例) 山田太郎", maxlength:"20" %>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">名前（フリガナ）</label>
      <span class="indispensable">必須</span>      
    </div>
    <%= f.text_area :full_name_kana, class:"input-default", id:"full_name_kana", placeholder:"例) ヤマダタロウ", maxlength:"20" %>
  </div>


  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">性別</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.collection_select(:gender_id, Gender.all, :id, :name, {}, {class:"gender-select"}) %>
  </div>


  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">血液型 ABO型</label>
    </div>
    <%= f.collection_select(:blood_abo_id, BloodAbo.all, :id, :name, {}, {class:"bloodabo-select"}) %>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">血液型 RH型</label>
    </div>
    <%= f.collection_select(:blood_rh_id, BloodRh.all, :id, :name, {}, {class:"bloodrh-select"}) %>
  </div>




  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">生年月日</label>
      <span class="indispensable">必須</span>
    </div>
    <div class='input-birth-wrap'>
      <%= raw sprintf(
                  f.date_select(
                    :date_of_birth,
                    class:'select-birth',
                    id:"date_of_birth",
                    use_month_numbers: true,
                    prompt:'--',
                    start_year: 1920,
                    end_year: (Time.now.year - 10),
                    date_separator: '%s'),
                  "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" %>
    </div>
  </div>



  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">移送区分</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.collection_select(:transfer_id, Transfer.all, :id, :name, {}, {class:"transfer-select"}) %>
  </div>



  <div class="patient-explain">
      <div class="weight-bold-text">
        <label class="form-text">既往歴</label>
      </div>
      <%= f.text_area :pmhx, class:"patient-text", id:"patient-info", placeholder:"既往歴（1,000文字まで）" , rows:"10" ,maxlength:"1000" %>
  </div>


  <div class="patient-explain">
      <div class="weight-bold-text">
        <label class="form-text">患者の補足情報</label>
      </div>
      <%= f.text_area :description, class:"patient-text", id:"patient-info", placeholder:"患者の補足情報（1,000文字まで）" , rows:"10" ,maxlength:"1000" %>
  </div>





<%#------ addresses テーブル部分 ------%>


      <h1 class='info-input-haedline'>
        患者の住所
      </h1>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">郵便番号</label>
        </div>
        <%= f.text_field :postal_code, class:"input-default", id:"postal-code", placeholder:"例）123-4567", maxlength:"8" %>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">都道府県</label>
        </div>
        <%= f.collection_select(:prefecture_id, Prefecture.all, :id, :name, {}, {class:"select-box", id:"prefecture"}) %>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">市区町村</label>
        </div>
        <%= f.text_field :city, class:"input-default", id:"city", placeholder:"例）横浜市緑区"%>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">番地</label>
        </div>
        <%= f.text_field :house_number, class:"input-default", id:"addresses", placeholder:"例）青山1-1-1"%>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">建物名</label>
        </div>
        <%= f.text_field :building_name, class:"input-default", id:"building", placeholder:"例）柳ビル103"%>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">電話番号</label>
        </div>
        <%= f.text_field :phone_number, class:"input-default", id:"phone-number", placeholder:"例）09012345678",maxlength:"11"%>
      </div>
      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">電話番号2</label>
        </div>
        <%= f.text_field :phone_number2, class:"input-default", id:"phone-number2", placeholder:"例）09012345678",maxlength:"11"%>
      </div>






<%#------ contacts テーブル部分 ------%>
<%#------ 連絡先１ ------%>
      <h1 class='info-input-haedline'>
        連絡先1 情報の入力
      </h1>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">名前（姓名）</label>
    </div>
    <%= f.text_area :full_name1, class:"input-default", id:"full_name1", placeholder:"例) 山田太郎", maxlength:"20" %>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">名前（フリガナ）</label>
    </div>
    <%= f.text_area :full_name_kana1, class:"input-default", id:"full_name_kana1", placeholder:"例) ヤマダタロウ", maxlength:"20" %>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">患者との関係</label>
    </div>
    <%= f.text_area :relation1, class:"input-default", id:"relation1", placeholder:"例) 父・母・息子・娘", maxlength:"20" %>
  </div>

      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">電話番号11</label>
        </div>
        <%= f.text_field :phone_number11, class:"input-default", id:"phone_number11", placeholder:"例）09012345678",maxlength:"11"%>
      </div>

      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">電話番号12</label>
        </div>
        <%= f.text_field :phone_number12, class:"input-default", id:"phone_number12", placeholder:"例）09012345678",maxlength:"11"%>
      </div>

  <div class="patient-explain">
      <div class="weight-bold-text">
        <label class="form-text">連絡先１の補足情報</label>
      </div>
      <%= f.text_area :description1, class:"patient-text", id:"description1", placeholder:"連絡先1の補足情報（1,000文字まで）" , rows:"10" ,maxlength:"1000" %>
  </div>


<%#------ 連絡先２ ------%>
      <h1 class='info-input-haedline'>
        連絡先2 情報の入力
      </h1>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">名前（姓名）</label>
    </div>
    <%= f.text_area :full_name2, class:"input-default", id:"full_name2", placeholder:"例) 山田太郎", maxlength:"20" %>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">名前（フリガナ）</label>
    </div>
    <%= f.text_area :full_name_kana2, class:"input-default", id:"full_name_kana2", placeholder:"例) ヤマダタロウ", maxlength:"20" %>
  </div>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">患者との関係</label>
    </div>
    <%= f.text_area :relation2, class:"input-default", id:"relation2", placeholder:"例) 父・母・息子・娘", maxlength:"20" %>
  </div>

      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">電話番号21</label>
        </div>
        <%= f.text_field :phone_number21, class:"input-default", id:"phonenumber21", placeholder:"例）09012345678",maxlength:"11"%>
      </div>

      <div class="form-group">
        <div class='form-text-wrap'>
          <label class="form-text">電話番号22</label>
        </div>
        <%= f.text_field :phone_number22, class:"input-default", id:"phone-number22", placeholder:"例）09012345678",maxlength:"11"%>
      </div>

  <div class="patient-explain">
      <div class="weight-bold-text">
        <label class="form-text">連絡先2の補足情報</label>
      </div>
      <%= f.text_area :description2, class:"patient-text", id:"pat-cont-rel-appendix2", placeholder:"連絡先2の補足情報（1,000文字まで）" , rows:"10" ,maxlength:"1000" %>
  </div>




<%#------ admissions テーブル部分 ------%>
<%#------ 入力項目なし ------%>





  <br>
  <br>
  <br>

  <div class='register-btn'>
    <%= f.submit "患者情報を登録" ,class:"register-pink-btn" %>
  </div>

  <br>

  <div class='not-register-btn'>
    <%= link_to '戻る', root_path, class: "not-register-blue-btn" %>
  </div>


</div>
<% end %>

app/views/patients/show.html.erb
<div class="wrapper">

  <div class="side-bar">
    <%= render "side_bar" %>
  </div>

  <div class="main-part">
    <%= render "main-header" %>
    <%= render "main-center-show" %>
    <%= render "main-footer" %>
  </div>

</div>

app/views/patients/xxxxxx_main-header-show.html.erb
<div class="main-header">
  <div class="main-header-wrap">

    <div class="main-header-ward">
      <select name="ward-num">
        <option value='2'>外来</option>
        <option value='3'>1病棟</option>
        <option value='4'>2病棟</option>
      </select>
    </div>



    <div class="main-header-contents">
    </div>
  </div>
</div>